"""models definition

Revision ID: 686b23ca3676
Revises: 
Create Date: 2021-02-25 08:49:49.747277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "686b23ca3676"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("is_private", sa.Boolean(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=200), nullable=False),
        sa.Column("ip_address", sa.String(length=16), nullable=False),
        sa.Column("is_banned", sa.Boolean(), nullable=True),
        sa.Column("date_joined", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("password_hash"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ("conversation_id",),
            ["conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ("sender_id",),
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users_conversations",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("conversation_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ("conversation_id",),
            ["conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ("user_id",),
            ["users.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_conversations")
    op.drop_table("messages")
    op.drop_table("users")
    op.drop_table("conversations")
    # ### end Alembic commands ###
